# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    exclude-paths:
      - "requirements/minimum-constraints.txt"
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    schedule:
      interval: weekly
    groups:
      codeql:
        patterns: ["github/codeql-action/*"]
  - package-ecosystem: npm
    directory: "/frontend"
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns: ["*"]
        update-types: ["minor", "patch"]
