import type { KleinJob, KleinOperator, KleinSubtask } from "../type/klein";

export const subtaskFixture = (
  overrides: Partial<KleinSubtask> = {},
): KleinSubtask => ({
  subtask_index: 0,
  status: "running",
  rows_in: 10,
  rows_out: 9,
  bytes_in: 100,
  bytes_out: 90,
  rows_in_per_second: 5,
  rows_out_per_second: 4,
  bytes_in_per_second: 50,
  bytes_out_per_second: 40,
  queued: 1,
  capacity: 100,
  busy_ns: 1000,
  backpressure_ns: 100,
  busy_percent: 25,
  backpressure_percent: 5,
  backpressure_events: 1,
  barriers_in: 2,
  barriers_out: 2,
  checkpoint_alignment_ms: 3,
  checkpoint_barrier_latency_ms: 4,
  checkpoint_state_size_bytes: 1024,
  last_checkpoint_id: 7,
  ...overrides,
});

export const operatorFixture = (
  overrides: Partial<KleinOperator> = {},
): KleinOperator => ({
  name: "map",
  op_id: 1,
  parallelism: 2,
  status: "running",
  rows_in: 10,
  rows_out: 9,
  bytes_in: 100,
  bytes_out: 90,
  rows_in_per_second: 5,
  rows_out_per_second: 4,
  bytes_in_per_second: 50,
  bytes_out_per_second: 40,
  queued: 1,
  capacity: 100,
  busy_ns: 1000,
  backpressure_ns: 100,
  busy_percent: 25,
  backpressure_percent: 5,
  instances: {
    running: 2,
    pending: 0,
    restarting: 0,
    finished: 0,
    cancelled: 0,
    failed: 0,
  },
  cpus: 1,
  gpus: 0,
  downstream: [],
  backpressure_events: 1,
  barriers_in: 2,
  barriers_out: 2,
  checkpoint_alignment_ms: 3,
  checkpoint_barrier_latency_ms: 4,
  checkpoint_state_size_bytes: 1024,
  last_checkpoint_id: 7,
  can_rescale: true,
  subtasks: [],
  ...overrides,
});

export const jobFixture = (overrides: Partial<KleinJob> = {}): KleinJob => ({
  job_id: "job-1",
  job_name: "Orders",
  namespace: "job-1",
  runtime_mode: "STREAMING",
  status: "RUNNING",
  created_at_ms: 1_700_000_000_000,
  started_at_ms: 1_700_000_001_000,
  updated_at_ms: 1_700_000_002_000,
  duration_ms: 5_000,
  dashboard_stale: false,
  overview: {
    operators: 1,
    task_instances: 2,
    rows_in: 10,
    rows_out: 9,
    bytes_in: 100,
    bytes_out: 90,
    restarts: 0,
    max_restarts: 3,
    restart_window_seconds: 60,
  },
  operators: [operatorFixture()],
  edges: [],
  checkpoints: {
    summary: {
      total: 1,
      completed: 1,
      failed: 0,
      in_progress: 0,
      state_size_bytes: 1024,
      last_persisted_snapshot_id: 7,
    },
    history: [],
    latest_path: "file:///checkpoints/chk-7",
  },
  configuration: { "execution.runtime-mode": "STREAMING" },
  status_history: [{ status: "RUNNING", timestamp_ms: 1_700_000_001_000 }],
  ...overrides,
});
